export const AxiosPaths = {
    LOG_IN: '/auth/login',
    REGISTRATION: '/auth/registration',
    CHECK_EMAIL: '/auth/check-email',
    CONFIRM_EMAIL: '/auth/confirm-email',
    FORGOT_PASS: '/confirm-email',
    CHANGE_PASSWORD: '/auth/change-password',
    FEEDBACK: '/feedback',
    TRANING: '/training',
    TRANING_CATALOG: '/catalogs/training-list',
    CREATE_TRANING: '/create-training',
    UPLOAD_IMAGE: '/upload-image',
    CURRENT_USER: '/user/me',
    USER: '/user',
    TARIFF_CATALOGS: '/catalogs/tariff-list',
    TARIFF: '/tariff',
    TRAINING_PALS: '/catalogs/training-pals',
    USER_JOINT_TRAINING_LIST: '/catalogs/user-joint-training-list',
    INVITE: '/invite',
};
